// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw04j3Im0oSX2VJDyy09VGKUKDypy5oJs',
    appId: '1:868076804356:ios:0138ada63ef51086b3d851',
    messagingSenderId: '868076804356',
    projectId: 'robotic-jet-440410-h5',
    storageBucket: 'robotic-jet-440410-h5.firebasestorage.app',
    iosBundleId: 'com.example.bClips',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWTq7Di76InymqIfgzZEYuwu3Zi2AtWek',
    appId: '1:868076804356:web:8535eb28b60defb7b3d851',
    messagingSenderId: '868076804356',
    projectId: 'robotic-jet-440410-h5',
    authDomain: 'robotic-jet-440410-h5.firebaseapp.com',
    storageBucket: 'robotic-jet-440410-h5.firebasestorage.app',
    measurementId: 'G-S1TTYDH6D9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTq7Di76InymqIfgzZEYuwu3Zi2AtWek',
    appId: '1:868076804356:web:8535eb28b60defb7b3d851',
    messagingSenderId: '868076804356',
    projectId: 'robotic-jet-440410-h5',
    authDomain: 'robotic-jet-440410-h5.firebaseapp.com',
    storageBucket: 'robotic-jet-440410-h5.firebasestorage.app',
    measurementId: 'G-S1TTYDH6D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZX9KgxB0HK8gy6rTcIpaDCmBEY0Z6YVk',
    appId: '1:868076804356:android:b325db1b2fda8263b3d851',
    messagingSenderId: '868076804356',
    projectId: 'robotic-jet-440410-h5',
    storageBucket: 'robotic-jet-440410-h5.firebasestorage.app',
  );

}